CREATE TABLE IF NOT EXISTS forms (
    id                  INTEGER     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name           VARCHAR     NOT NULL,
    is_bmstu_student    BOOLEAN     NOT NULL,
    university_name     VARCHAR                 DEFAULT NULL,
    passport            VARCHAR                 DEFAULT NULL,
    phone               VARCHAR                 DEFAULT NULL,
    email               VARCHAR     NOT NULL,
    study_group         VARCHAR                 DEFAULT NULL,
    telegram            VARCHAR     NOT NULL,
    activities          VARCHAR     NOT NULL,
    source              VARCHAR                 DEFAULT NULL,
    created_at          TIMESTAMPTZ NOT NULL    DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL    DEFAULT now(),
    deleted_at          TIMESTAMPTZ             DEFAULT NULL
);
